version: 0.2

phases:
  install:
    commands:
      - echo "Install aws cli"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
  pre_build:
    commands:
      - echo "Checking flutter version"
      - flutter --version
      - echo "Fetch dependencies"
      - flutter pub get
  build:
    commands:
      - echo "Build Flutter Web"
      - flutter build web
artifacts:
  files:
    - "**/*"
  base-directory: "build/web"
