version: 0.2


env:
  variables:
    DISTRIBUTION_ID: EM5V6FWU3M6C
    S3: www.khj-image-app.com
phases:
  install:
    commands:
      - echo "Install aws cli"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/install
  pre_build:
    commands:
      - echo "Checking flutter version"
      - flutter --version
      - echo "Fetch dependencies"
      - flutter pub get
  build:
    commands:
      - echo "Build Flutter Web"
      - flutter build web
  post_build:
    commands:
      - echo "Delete S3 files"
      - aws s3 rm s3://$S3 --recursive
      - echo "Sync S3"
      - aws s3 sync build/web/ s3://$S3/ 
      - echo "Invalidate CloudFront cache"
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
artifacts:
  files:
    - "**/*"
  base-directory: "build/web"
  name: flutter-frontend-artifact-$(date +%Y-%m-%d-%H-%M-%S)
