version: 0.2


env:
  variables:
    FLUTTER_VERSION: flutter_linux_3.16.7-stable

phases:
  pre_build:
    commands:
      - echo "Fetch dependencies"
      - flutter pub get
  build:
    commands:
      - echo "Run tests"
      - flutter test
      - echo "Build Flutter Web"
      - flutter build web
artifacts:
  files:
    - '**/*'
  base-directory: 'build/web'
